name: pull_request

on:
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE
          git checkout $GITHUB_SHA

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: taikiinoue45/mvtec:sandbox
          no-cache: true

      - name: Clean up
        if: always()
        run: ls -A1 | xargs rm -rf

  pytest:
    needs: [docker-build]
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:sandbox

    steps:
      - name: Test checksum
        run: pytest -v tests/test_checksum.py
        working-directory: /app/{{cookiecutter.upper_project_name}}

      - name: Test coverage
        run: pytest -v --cov={{cookiecutter.lower_project_name}} --cov-report=xml tests/test_coverage.py
        working-directory: /app/{{cookiecutter.upper_project_name}}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: {{cookiecutter.upper_project_name}}
          fail_ci_if_error: true
          working-directory: /app/{{cookiecutter.upper_project_name}}

      - name: Clean up
        if: always()
        run: ls -A1 | xargs rm -rf

  run-experiments:
    needs: [docker-build, pytest]
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:sandbox

    env:
      DATABRICKS_HOST: ${% raw %}${{ secrets.DATABRICKS_HOST }}{% endraw %}
      DATABRICKS_TOKEN: ${% raw %}${{ secrets.DATABRICKS_TOKEN }}{% endraw %}

    steps:
      - name: Run experiments
        run: |
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_bottle params.category=bottle
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_cable params.category=cable
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_capsule params.category=capsule
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_carpet params.category=carpet
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_grid params.category=grid
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_hazelnut params.category=hazelnut
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_leather params.category=leather
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_metal_nut params.category=metal_nut
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_pill params.category=pill
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_screw params.category=screw
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_tile params.category=tile
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_toothbrush params.category=toothbrush
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_transistor params.category=transistor
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_wood params.category=wood
          python run.py ./config.yaml params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/sandbox params.run_name={{cookiecutter.upper_project_name}}_zipper params.category=zipper
        working-directory: /app/{{cookiecutter.upper_project_name}}

      - name: Clean up
        if: always()
        run: ls -A1 | xargs rm -rf
